server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=springdatajdbc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true